@startuml "AWS Sequence Diagram"

title "Shortly - Rota não encontrada"

skinparam participantPadding 50
skinparam style strictuml

!define AWSPUML https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist

!include AWSPUML/AWSCommon.puml
!include AWSPUML/General/User.puml
!include AWSPUML/Compute/Lambda.puml
!include AWSPUML/ManagementGovernance/CloudWatch.puml
!include AWSPUML/ApplicationIntegration/APIGateway.puml
!include AWSPUML/ApplicationIntegration/APIGatewayEndpoint.puml

'!include AWSPUML/AWSSimplified.puml

UserParticipant(MyUser, "User", "Cliente")
APIGatewayParticipant(MyApiGateway, "Api Gateway", "Proxy Gateway")
APIGatewayEndpointParticipant(MyApiGatewayEndpoint, "Endpoint Lambda", "ANY /{proxy+}")
CloudWatchParticipant(MyCloudWatch, "Logs do Sistema", "Grupos de Logs")
LambdaParticipant(MyLambda, "Função Lambda", "src/functions/any.main")

autonumber 1.1
MyUser -> MyApiGateway : GET /some/unknown/route
autonumber 2.1
MyApiGateway -> MyApiGatewayEndpoint : Encaminha a solicitação para o endpoint Lambda ANY /{proxy+}
MyApiGateway -->> MyCloudWatch : Adiciona uma entrada nos logs contendo o RequestID, o método e a rota da solicitação
autonumber 3.1
MyApiGatewayEndpoint -> MyLambda : Invoca a função com o contexto de chamada e o evento APIGatewayProxyEventV2
autonumber 3.1
MyLambda --> MyApiGatewayEndpoint : Resposta genérica NotFound em formato JSON
autonumber 2.1
MyApiGatewayEndpoint --> MyApiGateway : Evento APIGatewayProxyResultV2 contendo o código e a mensagem de erros com status HTTP 404
autonumber 1.1
MyApiGateway --> MyUser : JSON contendo o código e a mensagem de erros com status HTTP 404

@enduml
