@startuml "AWS Sequence Diagram"

title "Shortly - Visualizar URL original"

skinparam participantPadding 35

!define AWSPUML https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist

!include AWSPUML/AWSCommon.puml
!include AWSPUML/General/User.puml
!include AWSPUML/General/Globe.puml
!include AWSPUML/Compute/Lambda.puml
!include AWSPUML/Database/DynamoDB.puml
!include AWSPUML/ManagementGovernance/CloudWatch.puml
!include AWSPUML/ApplicationIntegration/APIGateway.puml
!include AWSPUML/ApplicationIntegration/APIGatewayEndpoint.puml

'!include AWSPUML/AWSSimplified.puml

UserParticipant(MyUser, "User", "Cliente")
APIGatewayParticipant(MyApiGateway, "Api Gateway", "Proxy Gateway")
APIGatewayEndpointParticipant(MyApiGatewayEndpoint, "Endpoint Lambda", "GET /v1/code/{code}")
LambdaParticipant(MyLambda, "Função Lambda", "src/functions/code/{code}/get.main")
DynamoDBParticipant(MyDynamoDB, "Banco de Dados", "Banco de dados não-relacional")
CloudWatchParticipant(MyCloudWatch, "Logs do Sistema", "Grupos de Logs")
GlobeParticipant(MyGlobe, "Site Original", "Destino do usuário")

autonumber 1.1
MyUser -> MyApiGateway : GET /v1/code/{code}
autonumber 2.1
MyApiGateway -> MyApiGatewayEndpoint : Encaminha a solicitação para o endpoint Lambda apropriado
MyApiGateway -->> MyCloudWatch : Adiciona uma entrada nos logs contendo o RequestID, o método e a rota da solicitação
autonumber 3.1
MyApiGatewayEndpoint -> MyLambda : Invoca a função com o contexto de chamada e o evento APIGatewayProxyEventV2
autonumber 4.1
MyLambda -> MyDynamoDB : Localiza a URL encurtada pelo seu código
MyLambda -->> MyCloudWatch : Adiciona entradas nos logs para escritas e erros de execução
autonumber 4.1
MyDynamoDB --> MyLambda : Registro ShortUrl da URL encurtada
MyLambda -->> MyGlobe : HTTP Redirect 301 para o site original

@enduml
