@startuml "AWS Sequence Diagram"

title "Shortly - Solicitação de arquivos estáticos do front-end"

skinparam participantPadding 50
skinparam style strictuml

!define AWSPUML https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist

!include AWSPUML/AWSCommon.puml
!include AWSPUML/General/all.puml
!include AWSPUML/Storage/all.puml
!include AWSPUML/NetworkingContentDelivery/all.puml

'!include AWSPUML/AWSSimplified.puml

UserParticipant(MyUser, "User", "Cliente")
Route53Participant(MyRoute53, "Hosted Zone", "Resolvedor DNS")
CloudFrontParticipant(MyCloudFront, "Content Delivery Network", "Provedor de Cache")
SimpleStorageServiceParticipant(MyS3, "Bucket Privado", "Repositório de arquivos")

autonumber 1.1
MyUser -> MyRoute53 : Solicita registro DNS A ou AAAA do domínio
autonumber 2.1
MyRoute53 -> MyCloudFront : Resolve para o CloudFront
autonumber 3.1
alt "Recurso está em cache?" : "Caso o cache seja inválido ou tenha expirado"
  MyCloudFront -> MyS3 : Lê os arquivos do Bucket e armazena em Cache por 86400s
  autonumber 3.1
  MyS3 -->> MyCloudFront : Arquivos solicitados
else "Caso o cache seja válido"
  MyCloudFront -> MyCloudFront : Lê os arquivos do S3 previamente armazenados em cache
end
autonumber 2.1 
MyCloudFront -->> MyRoute53 : Arquivos solicitados
autonumber 1.1 
MyRoute53 -->> MyUser : Arquivos solicitados

@enduml
